In [2]:
import numpy as np

## 1. 1차원 배열

In [9]:
# 아래는 배열이 아닌 list 이며 모양은 비슷함
a1 = [1, 2, 3, 4, 5, 10, 20, "가", "나"]
print(type(a1))
print(a1)
# print(a1.shape)      #list에서는 shape을 사용못함, 에러

<class 'list'>
[1, 2, 3, 4, 5, 10, 20, '가', '나']


In [10]:
#리스트와 배열의 차이는 , 의 차이

a1 = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"])
print(a1)
print(type(a1))
print(a1.shape)   #shape는 배열의 모양,크기  - 여기서는 a1 배열이 7개의 데이터로 1차원이므로 (7,) 로 표현
print(a1.dtype)   #숫자는 1byte, 문자는 아스키코드로 표현 2byte 씩이므로 총 11 자리

['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
<U11


In [13]:
# a1 = np.array([1, 2, 3, 4, 5, 10, 20], dtype=float)
a1 = np.array([1, 2, 3, 4, 5, 10, 20], float)
print(a1)
print(a1.dtype)

[ 1.  2.  3.  4.  5. 10. 20.]
float64


In [14]:
##### 벡터화 연산  (1차원 배열로 연산할 수 있게끔 만드는 것을 의미)

data1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(data1 * 3)   # list는 수학적 연산이 불가능하다
#print(data1 - 3)   # 에러

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
dataArray = np.array(data1)

print(dataArray * 2)
print(dataArray - 2)
print(dataArray + 2)

[ 0  2  4  6  8 10 12 14 16 18]
[-2 -1  0  1  2  3  4  5  6  7]
[ 2  3  4  5  6  7  8  9 10 11]


In [17]:
##### 인덱스 접근
print(dataArray[0], dataArray[1])

0 1


## 2. 2차원 배열

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.shape)    #2행 3열에 대한 표시

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
(2, 3)


## 3. 3차원 배열

In [30]:
arr = np.array([[[1, 2, 3, 4], [3, 4, 5, 6]], 
                [[7, 8, 9, 10], [11, 12, 13, 14]]])

print(arr)
print(arr.shape)   #4열짜리를 2번 묶고 또 그런 배열이 2개가 있다는 뜻. 곧 3차원을 의미
print(arr.ndim)   #몇차원 배열인지 숫자로 나타내줌
print("---------------------------------")
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])
print(len(arr))  #2차원배열 2개를 관리하므로 2
print(len(arr[0])) #1차원배열 2개를 관리하므로 2
print(len(arr[0][0]))

[[[ 1  2  3  4]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [11 12 13 14]]]
(2, 2, 4)
3
---------------------------------
[[1 2 3 4]
 [3 4 5 6]]
[1 2 3 4]
1
2
2
4


In [32]:
#대괄호의 갯수를 보고 몇차원인지 알수도 있다.

arr = np.array([[[[10]]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[10]]]]
(1, 1, 1, 1)
4


## 4. 집계 함수

In [35]:
x = np.random.randn(8)            #()안에 입력한 숫자의 갯수만큼 난수를 랜덤으로 구해줌
y = np.random.randn(8)

print(x)
print(y)
print(type(x)) # numpy를 통해 나온 결과값은 배열,  결과도 보면 ,가 없다

[ 0.73260638 -0.09163591 -0.88466111 -0.41378421 -0.86357503 -0.58608405
  0.80474366  0.1542453 ]
[ 0.36106618 -1.40118437 -0.76984119 -0.8301113  -1.10903178 -0.40674953
 -0.2931908  -1.25212293]
<class 'numpy.ndarray'>


In [36]:
np.maximum(x, y)  #2개를 비교해서 큰것만 나열

array([ 0.73260638, -0.09163591, -0.76984119, -0.41378421, -0.86357503,
       -0.40674953,  0.80474366,  0.1542453 ])

In [37]:
arr = np.random.randn(5, 4)    #2차원 배열 ,  5행 4열짜리
arr

array([[-0.36392439,  1.15954801, -2.01451807, -0.73618475],
       [-1.66836809, -0.07324414,  0.31593526, -1.34500283],
       [ 0.14494746,  0.86611213,  0.16374392,  0.33938239],
       [-0.64089668,  0.94555156,  0.61014399,  0.54801833],
       [ 0.32824199, -0.38320164,  1.95944399, -0.06054335]])

In [44]:
#앞에 ?를 붙이면 사용법을 알려주는 안내창이 뜸

# ?np.sum 

print(arr.sum())    #전체 합계
print(arr.sum(axis=0))  #열의 합계
print(arr.sum(axis=1))  #행의 합계

0.09518509481353596
[-2.19999971  2.51476592  1.03474909 -1.2543302 ]
[-1.95507919 -2.7706798   1.5141859   1.4628172   1.84394099]


## 5. 배열의 인덱싱

In [45]:
arr = np.array([100, 200, 300, 400, 500])

print(arr[2], arr[4], arr[-1], arr[-3])

300 500 500 300


In [47]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr[0][1], arr[0, 2], arr[-1, -1])

1 2 5


In [46]:
temp = [[0, 1, 2], [3, 4, 5]]   #이건 배열이 아닌 리스트라는 점 잊지말자
print(temp[0][1])

1


In [53]:
##### fancy index

arr = np.array([i for i in range(10)])
print(arr)

#boolean의 특성을 이용하여 짝수만 골라내보기
idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr[idx])

print(arr[arr % 2 == 0])

# arr에서 3의 배수를 찾아라

print(arr[arr % 3 == 0])

# arr에서 4로 나누면 1이 남는 수를 찾아라

print(arr[arr % 4 == 1])

# arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라

print(arr[(arr % 3 == 0) & (arr % 4 ==1)])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


## 6. 배열의 슬라이싱

In [60]:
arr = np.array([[0, 1, 2, 3],
               [4, 5, 6, 7],
               [8, 9, 10, 11]])

arr

print(arr[0, 0:2])
print("----------------")
print(arr[1:3, 0:2])
print("----------------")
print(arr[0, :])
print("----------------")
print(arr[[2, 1, 0], :])   #행의 순서를 바꿀수도 있다
print("----------------")
print(arr[:, [0,3]])

[0 1]
----------------
[[4 5]
 [8 9]]
----------------
[0 1 2 3]
----------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
----------------
[[ 0  3]
 [ 4  7]
 [ 8 11]]


## 7. numpy 자료형

+ b : 불리언
+ i : 정수형
+ u : 부호없는 정수형
+ f : 부동 소수점
+ c : 복소수
+ 0 : 객체
+ S : 바이트 문자열
+ U : 유니코드 문자열

In [61]:
# a1 = np.dtype("i")
a1 = np.dtype("i8")
print(a1)

int64


In [65]:
# arr = np.array([1, 2, 3], dtype="f")
arr = np.array([1, 2, 3], dtype=np.float16)
print(arr.dtype)
print(arr[0] + arr[1])

print("--------------------------------------------")

arr = np.array([1, 2, 3], dtype="U")
print(arr.dtype)
print(arr[0] + arr[1])   #유니코드, 문자열은 수학적연산이 아닌 연결


float16
3.0
--------------------------------------------
<U1
12


## 8. 배열 생성

In [74]:
arr = np.zeros(5)
print(arr)
print(arr.dtype)
print(type(arr))

print("--------------------------------------------")

arr = np.zeros(5, dtype="i8")
print(arr)
print(arr.dtype)

print("--------------------------------------------")

#데이터타입에서 유니코드(U)는 한글자를 2byte로 처리하므로 U4는 8byte이다.
#데이터타입에서 바이트문자열(S)는 한글자를 1byte로 처리하므로 S4는 4byte이다.
#데이터타입을 바이트문자열(S)로 지정하면 앞에 b가 붙는데 이는 글자하나를 1byte로 처리하겠다는 표시다.

# 바이트문자열 결과예시
# [b'' b'' b'' b'' b'']
# |S4
# [b'abc' b'abcd' b'abcd' b'' b'']

arr = np.zeros(5, dtype="S4")
print(arr)
print(arr.dtype)

arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde"   #dtype을 유니코드4 자리로 제한을 걸어둬서 abcd까지만 들어가고 e는 못들어간다.
print(arr)

print("--------------------------------------------")

print(np.zeros((2,3)))   #2행3열짜리  , 튜플로 묶음

[0. 0. 0. 0. 0.]
float64
<class 'numpy.ndarray'>
--------------------------------------------
[0 0 0 0 0]
int64
--------------------------------------------
[b'' b'' b'' b'' b'']
|S4
[b'abc' b'abcd' b'abcd' b'' b'']
--------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


In [92]:
arr = np.ones((2, 3, 4))
print(arr)

print("--------------------------------------------")

arr = np.zeros((2, 3))
arr2 = np.ones_like(arr)    # 0을 1로 바꿔주는 기능 ones_like()
print(arr2)

print("--------------------------------------------")

arr = np.empty((4, 3))   # empty는 초기화를 안하겠다는 의미, 기존에 작업했던 쓸모없는 데이터를 가져다가 채우는 것
print(arr)

print("--------------------------------------------")

arr = np.arange(10)    # 파이썬의 기본함수중에 range()는 list로 결과값을 출력,  numpy의 arange는 배열로 결과값을 출력
print(arr)

print("--------------------------------------------")

arr = np.linspace(1, 100, 5)    # linspace(1부터 100까지 5등분)
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
--------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------
[[1.01855798e-312 1.06099790e-312 1.01855798e-312]
 [9.54898106e-313 1.06099790e-312 1.01855798e-312]
 [1.23075756e-312 1.14587773e-312 1.03977794e-312]
 [9.76118064e-313 1.06099790e-312 1.90979621e-312]]
--------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------
[  1.    25.75  50.5   75.25 100.  ]


## 9. 전치 연산(Transpose)  - 행은 열로, 열은 행으로 바꾸는

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.T)  #소문자 t는 사용불가, 무조건 대문자 T

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 10. 배열의 크기 변형 : reshape(), flatten(), ravel()

In [96]:
arr = np.arange(12)
print(arr)
print(arr.shape)  #데이터 크기 확인 (12,)는 12개에 1차원 이라는 의미

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [102]:
arr1 = arr.reshape(3, 4)   # reshape을 이용해서 3행4열로 변경하기
print(arr1)
print(arr1.shape)

print("------------------------------------")

arr1 = arr.reshape(3, -1)   # 여기서 -1 은 행이 정해지면 자동적으로 열 계산을 하겠다는 의미,  index에서는 끝이지만 여기서는 아님
print(arr1)
print(arr1.shape)

print("------------------------------------")

arr1 = arr.reshape(-1, 4)  # 여기서 -1은 열이 정해지면 자동적으로 행 계산을 하겠다는 의미, index에서는 끝이지만 여기서는 아님
print(arr1)
print(arr1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [104]:
arr2 = arr.reshape(2, 2, 3)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(2, 2, -1)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(2, -1, 3)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(-1, 2, 3)
print(arr2)
print(arr2.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [108]:
print(arr1.flatten())  # flatten() 과 ravel()은 기능이 같으며 1차원 배열로 바꿔주는 기능이다.
print(arr1.ravel())

print("--------------------------------")

print(arr2.flatten())
print(arr2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [116]:
arr = np.arange(5)

print(arr.reshape(1, 5))
print(arr.reshape(5, 1))

# reshape는 복사본에다가 변경하는 것이므로 print(arr.shape)로 찍어보면 바뀌지 않은 원본의 결과인 (5,) 이 나온다.
# 원본 데이터를 변경하려면 arr = arr.reshape(1, 5) 이렇게 해야한다.

print("----------------------------")

print(arr[:, np.newaxis])  # np.newaxis 는 [] 를 한번 덧씌워주는 역할


[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
----------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
(5,)
