In [2]:
import numpy as np

## 1. 1차원 배열

In [9]:
# 아래는 배열이 아닌 list 이며 모양은 비슷함
a1 = [1, 2, 3, 4, 5, 10, 20, "가", "나"]
print(type(a1))
print(a1)
# print(a1.shape)      #list에서는 shape을 사용못함, 에러

<class 'list'>
[1, 2, 3, 4, 5, 10, 20, '가', '나']


In [10]:
#리스트와 배열의 차이는 , 의 차이

a1 = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나"])
print(a1)
print(type(a1))
print(a1.shape)   #shape는 배열의 모양,크기  - 여기서는 a1 배열이 7개의 데이터로 1차원이므로 (7,) 로 표현
print(a1.dtype)   #숫자는 1byte, 문자는 아스키코드로 표현 2byte 씩이므로 총 11 자리

['1' '2' '3' '4' '5' '10' '20' '가' '나']
<class 'numpy.ndarray'>
(9,)
<U11


In [13]:
# a1 = np.array([1, 2, 3, 4, 5, 10, 20], dtype=float)
a1 = np.array([1, 2, 3, 4, 5, 10, 20], float)
print(a1)
print(a1.dtype)

[ 1.  2.  3.  4.  5. 10. 20.]
float64


In [14]:
##### 벡터화 연산  (1차원 배열로 연산할 수 있게끔 만드는 것을 의미)

data1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(data1 * 3)   # list는 수학적 연산이 불가능하다
#print(data1 - 3)   # 에러

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
dataArray = np.array(data1)

print(dataArray * 2)
print(dataArray - 2)
print(dataArray + 2)

[ 0  2  4  6  8 10 12 14 16 18]
[-2 -1  0  1  2  3  4  5  6  7]
[ 2  3  4  5  6  7  8  9 10 11]


In [17]:
##### 인덱스 접근
print(dataArray[0], dataArray[1])

0 1


## 2. 2차원 배열

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr.shape)    #2행 3열에 대한 표시

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
(2, 3)


## 3. 3차원 배열

In [30]:
arr = np.array([[[1, 2, 3, 4], [3, 4, 5, 6]], 
                [[7, 8, 9, 10], [11, 12, 13, 14]]])

print(arr)
print(arr.shape)   #4열짜리를 2번 묶고 또 그런 배열이 2개가 있다는 뜻. 곧 3차원을 의미
print(arr.ndim)   #몇차원 배열인지 숫자로 나타내줌
print("---------------------------------")
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])
print(len(arr))  #2차원배열 2개를 관리하므로 2
print(len(arr[0])) #1차원배열 2개를 관리하므로 2
print(len(arr[0][0]))

[[[ 1  2  3  4]
  [ 3  4  5  6]]

 [[ 7  8  9 10]
  [11 12 13 14]]]
(2, 2, 4)
3
---------------------------------
[[1 2 3 4]
 [3 4 5 6]]
[1 2 3 4]
1
2
2
4


In [32]:
#대괄호의 갯수를 보고 몇차원인지 알수도 있다.

arr = np.array([[[[10]]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[10]]]]
(1, 1, 1, 1)
4


## 4. 집계 함수

In [35]:
x = np.random.randn(8)            #()안에 입력한 숫자의 갯수만큼 난수를 랜덤으로 구해줌
y = np.random.randn(8)

print(x)
print(y)
print(type(x)) # numpy를 통해 나온 결과값은 배열,  결과도 보면 ,가 없다

[ 0.73260638 -0.09163591 -0.88466111 -0.41378421 -0.86357503 -0.58608405
  0.80474366  0.1542453 ]
[ 0.36106618 -1.40118437 -0.76984119 -0.8301113  -1.10903178 -0.40674953
 -0.2931908  -1.25212293]
<class 'numpy.ndarray'>


In [36]:
np.maximum(x, y)  #2개를 비교해서 큰것만 나열

array([ 0.73260638, -0.09163591, -0.76984119, -0.41378421, -0.86357503,
       -0.40674953,  0.80474366,  0.1542453 ])

In [37]:
arr = np.random.randn(5, 4)    #2차원 배열 ,  5행 4열짜리
arr

array([[-0.36392439,  1.15954801, -2.01451807, -0.73618475],
       [-1.66836809, -0.07324414,  0.31593526, -1.34500283],
       [ 0.14494746,  0.86611213,  0.16374392,  0.33938239],
       [-0.64089668,  0.94555156,  0.61014399,  0.54801833],
       [ 0.32824199, -0.38320164,  1.95944399, -0.06054335]])

In [44]:
#앞에 ?를 붙이면 사용법을 알려주는 안내창이 뜸

# ?np.sum 

print(arr.sum())    #전체 합계
print(arr.sum(axis=0))  #열의 합계
print(arr.sum(axis=1))  #행의 합계

0.09518509481353596
[-2.19999971  2.51476592  1.03474909 -1.2543302 ]
[-1.95507919 -2.7706798   1.5141859   1.4628172   1.84394099]


## 5. 배열의 인덱싱

In [45]:
arr = np.array([100, 200, 300, 400, 500])

print(arr[2], arr[4], arr[-1], arr[-3])

300 500 500 300


In [47]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
print(arr[0][1], arr[0, 2], arr[-1, -1])

1 2 5


In [46]:
temp = [[0, 1, 2], [3, 4, 5]]   #이건 배열이 아닌 리스트라는 점 잊지말자
print(temp[0][1])

1


In [53]:
##### fancy index

arr = np.array([i for i in range(10)])
print(arr)

#boolean의 특성을 이용하여 짝수만 골라내보기
idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr[idx])

print(arr[arr % 2 == 0])

# arr에서 3의 배수를 찾아라

print(arr[arr % 3 == 0])

# arr에서 4로 나누면 1이 남는 수를 찾아라

print(arr[arr % 4 == 1])

# arr에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라

print(arr[(arr % 3 == 0) & (arr % 4 ==1)])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


## 6. 배열의 슬라이싱

In [60]:
arr = np.array([[0, 1, 2, 3],
               [4, 5, 6, 7],
               [8, 9, 10, 11]])

arr

print(arr[0, 0:2])
print("----------------")
print(arr[1:3, 0:2])
print("----------------")
print(arr[0, :])
print("----------------")
print(arr[[2, 1, 0], :])   #행의 순서를 바꿀수도 있다
print("----------------")
print(arr[:, [0,3]])

[0 1]
----------------
[[4 5]
 [8 9]]
----------------
[0 1 2 3]
----------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
----------------
[[ 0  3]
 [ 4  7]
 [ 8 11]]


## 7. numpy 자료형

+ b : 불리언
+ i : 정수형
+ u : 부호없는 정수형
+ f : 부동 소수점
+ c : 복소수
+ 0 : 객체
+ S : 바이트 문자열
+ U : 유니코드 문자열

In [61]:
# a1 = np.dtype("i")
a1 = np.dtype("i8")
print(a1)

int64


In [65]:
# arr = np.array([1, 2, 3], dtype="f")
arr = np.array([1, 2, 3], dtype=np.float16)
print(arr.dtype)
print(arr[0] + arr[1])

print("--------------------------------------------")

arr = np.array([1, 2, 3], dtype="U")
print(arr.dtype)
print(arr[0] + arr[1])   #유니코드, 문자열은 수학적연산이 아닌 연결


float16
3.0
--------------------------------------------
<U1
12


## 8. 배열 생성

In [74]:
arr = np.zeros(5)
print(arr)
print(arr.dtype)
print(type(arr))

print("--------------------------------------------")

arr = np.zeros(5, dtype="i8")
print(arr)
print(arr.dtype)

print("--------------------------------------------")

#데이터타입에서 유니코드(U)는 한글자를 2byte로 처리하므로 U4는 8byte이다.
#데이터타입에서 바이트문자열(S)는 한글자를 1byte로 처리하므로 S4는 4byte이다.
#데이터타입을 바이트문자열(S)로 지정하면 앞에 b가 붙는데 이는 글자하나를 1byte로 처리하겠다는 표시다.

# 바이트문자열 결과예시
# [b'' b'' b'' b'' b'']
# |S4
# [b'abc' b'abcd' b'abcd' b'' b'']

arr = np.zeros(5, dtype="S4")
print(arr)
print(arr.dtype)

arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde"   #dtype을 유니코드4 자리로 제한을 걸어둬서 abcd까지만 들어가고 e는 못들어간다.
print(arr)

print("--------------------------------------------")

print(np.zeros((2,3)))   #2행3열짜리  , 튜플로 묶음

[0. 0. 0. 0. 0.]
float64
<class 'numpy.ndarray'>
--------------------------------------------
[0 0 0 0 0]
int64
--------------------------------------------
[b'' b'' b'' b'' b'']
|S4
[b'abc' b'abcd' b'abcd' b'' b'']
--------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]


In [92]:
arr = np.ones((2, 3, 4))
print(arr)

print("--------------------------------------------")

arr = np.zeros((2, 3))
arr2 = np.ones_like(arr)    # 0을 1로 바꿔주는 기능 ones_like()
print(arr2)

print("--------------------------------------------")

arr = np.empty((4, 3))   # empty는 초기화를 안하겠다는 의미, 기존에 작업했던 쓸모없는 데이터를 가져다가 채우는 것
print(arr)

print("--------------------------------------------")

arr = np.arange(10)    # 파이썬의 기본함수중에 range()는 list로 결과값을 출력,  numpy의 arange는 배열로 결과값을 출력
print(arr)

print("--------------------------------------------")

arr = np.linspace(1, 100, 5)    # linspace(1부터 100까지 5등분)
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
--------------------------------------------
[[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------
[[1.01855798e-312 1.06099790e-312 1.01855798e-312]
 [9.54898106e-313 1.06099790e-312 1.01855798e-312]
 [1.23075756e-312 1.14587773e-312 1.03977794e-312]
 [9.76118064e-313 1.06099790e-312 1.90979621e-312]]
--------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------
[  1.    25.75  50.5   75.25 100.  ]


## 9. 전치 연산(Transpose)  - 행은 열로, 열은 행으로 바꾸는

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.T)  #소문자 t는 사용불가, 무조건 대문자 T

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 10. 배열의 크기 변형 : reshape(), flatten(), ravel()

In [96]:
arr = np.arange(12)
print(arr)
print(arr.shape)  #데이터 크기 확인 (12,)는 12개에 1차원 이라는 의미

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [102]:
arr1 = arr.reshape(3, 4)   # reshape을 이용해서 3행4열로 변경하기
print(arr1)
print(arr1.shape)

print("------------------------------------")

arr1 = arr.reshape(3, -1)   # 여기서 -1 은 행이 정해지면 자동적으로 열 계산을 하겠다는 의미,  index에서는 끝이지만 여기서는 아님
print(arr1)
print(arr1.shape)

print("------------------------------------")

arr1 = arr.reshape(-1, 4)  # 여기서 -1은 열이 정해지면 자동적으로 행 계산을 하겠다는 의미, index에서는 끝이지만 여기서는 아님
print(arr1)
print(arr1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [104]:
arr2 = arr.reshape(2, 2, 3)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(2, 2, -1)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(2, -1, 3)
print(arr2)
print(arr2.shape)

print("----------------------------------")

arr2 = arr.reshape(-1, 2, 3)
print(arr2)
print(arr2.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
----------------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [108]:
print(arr1.flatten())  # flatten() 과 ravel()은 기능이 같으며 1차원 배열로 바꿔주는 기능이다.
print(arr1.ravel())

print("--------------------------------")

print(arr2.flatten())
print(arr2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [116]:
arr = np.arange(5)

print(arr.reshape(1, 5))
print(arr.reshape(5, 1))

# reshape는 복사본에다가 변경하는 것이므로 print(arr.shape)로 찍어보면 바뀌지 않은 원본의 결과인 (5,) 이 나온다.
# 원본 데이터를 변경하려면 arr = arr.reshape(1, 5) 이렇게 해야한다.

print("----------------------------")

print(arr[:, np.newaxis])  # np.newaxis 는 [] 를 한번 덧씌워주는 역할


[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
----------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
(5,)


## 11. 배열 연결(병합) : hstack, vstack, dstack, stack, tile

+ hstack(), vstack()

In [8]:
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 2))

print(arr1)
print(arr2)

arr3 = np.hstack([arr1, arr2])   # hstack 은 수평(행)으로 합치기,  vstack은 수직(열)으로 합치기 - 행과 열의 갯수가 일치시
print(arr3)


[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


+ dstack()

     1. dstack 은 기본값이 맨 뒷자리에 합칠 배열의 수가 위치

In [7]:
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))   # 두 개의 같은 크기의 배열을 준비 (3행4열짜리)

arr3 = np.dstack([arr1, arr2])  # 결과는 3행2열짜리 3차원 배열구조
print(arr3)
print(arr3.shape)

# dstack 은 몇개의 배열을 합칠꺼냐(즉, 합칠배열숫자)가 맨위로 추가가 된다. 3행4열짜리 2개 합칠시 (3,4,2) 구조

# 3, 4, 2

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)


In [9]:
# dstack 다른 예제

arr1 = [1, 2, 3]
arr2 = [4, 5, 6]

arr = np.dstack([arr1, arr2])
print(arr)
print(arr.shape)   # 3행2열짜리 1개로 만들어진다.

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [11]:
arr1 = np.ones((3, 4))
arr2 = np.ones((3, 4))
arr3 = np.ones((3, 4))

arr4 = np.dstack([arr1, arr2, arr3])   # 3행4열짜리 배열을 3개 합치니 (3, 4, 3) 이고 생성될때 4행3열짜리 3개 구조로 출력

print(arr4)
print(arr4.shape)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
(3, 4, 3)


+ stack()

     1. stack 은 기본값이 맨 앞자리에 합칠 배열의 수가 위치

In [12]:
# axis = 0    , 0 이 default (맨 앞)
arr1 = np.ones((3, 4))  
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2])  # 3행 4열짜리 배열 2개를 합치는,   (2, 3, 4)

print(arr3)
print(arr3.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


In [13]:
# axis = 1 일때
arr1 = np.ones((3, 4))  
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2], axis=1)  # 3행 4열짜리 배열 2개를 합치는, 단 합치는 수의 위치를 1로 지정

print(arr3)
print(arr3.shape)    # (3, 2, 4)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(3, 2, 4)


In [14]:
# axis = 2 일때   (이 예제에서는 dstack과 동일한 결과)
arr1 = np.ones((3, 4))  
arr2 = np.ones((3, 4))

arr3 = np.stack([arr1, arr2], axis=2)  # 3행 4열짜리 배열 2개를 합치는, 단 합치는 수의 위치를 2로 지정

print(arr3)
print(arr3.shape)    # (3, 4, 2)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(3, 4, 2)


+ tile()

In [24]:
A = 1
B = np.array([0, 1])
C = np.array([[0, 1], [2, 3]])

print(np.tile(A, 3))
print(np.tile(B, 3))
print(np.tile(C, 3))
print("-----------------------------------")
print(np.tile(A,(2,3)))
print(np.tile(B,(2,3)))
print(np.tile(C,(2,3)))
print("-----------------------------------")
print(np.tile(B,(4,2,3)))   #데이터를 3개씩 2번 4개로

[1 1 1]
[0 1 0 1 0 1]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]
-----------------------------------
[[1 1 1]
 [1 1 1]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]
-----------------------------------
[[[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]

 [[0 1 0 1 0 1]
  [0 1 0 1 0 1]]]


## 12. BroadCasting

+ 크기가 서로 다른 행렬(벡터)끼리 연산을 가능하게 하는 것

In [38]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
print(x)

#풀이
# range(7) = [0, 1, 2, 3, 4, 5, 6] 를 의미
# [i:i+3] = range7을 슬라이싱하는 자리수, 처음에는 i가 0일테니 [0:3] 즉 0,1,2 자리 수를 뽑아오게됨
# for i in range(5) = [0, 1, 2, 3, 4]  , 반복문을 돌면서 5번을 시행하겠다는 의미

y = np.arange(5)[:, np.newaxis]
print(y)

print(x + y)   #브로드캐스팅이 지원되기때문에 서로 크기가 다른 x와 y가 연산이 가능해짐

y = np.arange(3)    # 열의 갯수는 맞아야 계산이 된다는 점...
print(y)
print(x + y)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
[0 1 2]
[[0 2 4]
 [1 3 5]
 [2 4 6]
 [3 5 7]
 [4 6 8]]


In [26]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [29]:
[range(7)[i:i+3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [32]:
range(7)[1:1+3]

range(1, 4)

## 13. 차원 축소(dimension reduction) 연산

+ 최대값 / 최소값 : max(), min(), argmax(), argmin()
+ 대표값 : sum(), mean(), median(), std(), var()

+ 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 된다.       이러한 연산을 차원 축소 연산이라고 한다.

In [44]:
x = np.array([1, 3, 2, -3])

print(x.max())
print(x.min())

print("-----------------------------")

print(np.argmax(x))   # argmax 는 최대값이 있는 index를 알려준다
print(np.argmin(x))   # argmin 는 최소값이 있는 index를 알려준다

3
-3
-----------------------------
1
3


## 14. 기술 통계   - 여기서 기술은 서술하다 의미 (데이터 탐색할 때 사용하는 함수들)

+ sum(), mean()
+ val(), std()
+ max(), min()
+ median()
+ percentile()
+ ...

## 15. 정렬

In [47]:
arr = np.array([[4, 3, 5, 7],
               [1, 12, 11, 9],
               [2, 15, 1, 14]])

print(np.sort(arr))
print(np.sort(arr, axis=1))  # 행 기준으로 정렬, 1이 default
print(np.sort(arr, axis=0))  # 열 기준으로 정렬

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]


In [48]:
print(arr)

#위에서 정렬했던 것과 다르게 원본데이터는 그대로 유지.  왜냐, 위에서 정렬은 원본을 변경한게 아닌 복사본으로 시행한 결과를 나타냄

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]


In [51]:
##### argsort()

arr = np.array([42, 38, 12, 25])
idx = np.argsort(arr)   # 오름차순으로 인덱스(index) 값을 나타내주는 것
print(idx)


[2 3 1 0]


In [55]:
np.sort(arr)    #오름차순 기본
np.sort(arr)[::-1]    #내림차순 [시작, 끝, 스탭]

array([42, 38, 25, 12])

In [60]:
print(np.argsort(-arr))
arr[np.argsort(-arr)]

[0 1 3 2]


array([42, 38, 25, 12])

## 16. 난수

+ rand() : 0 ~ 1 사이의 균일 분포
+ randn() : 표준 정규 분포 ( 음수 포함 )
+ randint() : 균일 분포의 정수

In [64]:
print(np.random.rand(10))  #0과 1 사이에서 10개의 랜덤으로 수를 뽑음
print("---------------------------------------------------------------")
print(np.random.rand(3, 5))   #0과 1 사이에서 3행 5열로 랜덤으로 수를 뽑음

[0.72074634 0.52635604 0.90505487 0.99174453 0.53885596 0.43019342
 0.69484302 0.48593558 0.4859224  0.02220957]
---------------------------------------------------------------
[[0.76618352 0.37841385 0.96919599 0.30219983 0.85939126]
 [0.92100675 0.37724381 0.70101807 0.20930031 0.17313887]
 [0.39812964 0.18163544 0.64144145 0.82400551 0.33986119]]


In [70]:
print(np.random.randint(10))    #() 안에 들어가는 숫자가 범위, 여기서는 0~9까지 정수를 랜덤으로 뽑음
print("--------------------------")
print(np.random.randint(11, 20))    # 11부터 19까지 정수를 랜덤으로 뽑음
print("--------------------------")
print(np.random.randint(11, 20, size=100))   # 11부터 19까지 랜덤정수를 100개를 뽑음
print("--------------------------")
print(np.random.randint(11, 20, size=(3, 4)))  # 11부터 19까지 랜덤정수를 3행4열로 뽑음

8
--------------------------
13
--------------------------
[17 15 12 11 17 13 16 18 16 19 19 17 14 14 11 13 15 11 14 19 12 12 14 19
 12 12 11 16 12 16 12 17 13 18 18 18 11 17 12 14 11 15 16 16 17 11 14 16
 19 18 12 19 11 15 17 15 16 17 14 18 16 13 15 17 14 19 14 16 13 18 13 12
 18 12 15 16 11 15 15 11 13 11 18 17 13 12 14 19 17 16 14 15 16 15 17 17
 17 14 12 14]
--------------------------
[[11 16 11 11]
 [17 19 13 13]
 [15 12 15 19]]


In [73]:
##### 재현성(난수 고정)

np.random.seed(100)

np.random.rand(3)

array([0.54340494, 0.27836939, 0.42451759])

In [78]:
##### 데이터의 순서 바꾸기

x = np.arange(10)
print(x)

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 2 1 6 9 8 7 4 3 5]


In [84]:
##### 샘플링 : 복원(default), 비복원

#복원추출 예시 - 예를들어 앞에서 0이 뽑혔어도 다음에 0이 뽑힐 수 있음
print(np.random.choice(5, 7))   #여기서 5는 0부터 4까지, 7은 7번 뽑겠다는 횟수의 의미   ( 몇개의 데이터에서,  몇번을 뽑을건지)
print("----------------------------")
#비복원 추출 예시 - 예를들어 앞에서 0이 뽑히면 0을제외한 나머지 수를 뽑음, 즉 한번 뽑은 값은 다시 나올 수 없음
print(np.random.choice(5, 5, replace=False))
print("----------------------------")
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))  # p는 확률을 의미하며 0부터 4까지 나올 수의 확률을 최소0 최대 1로 지정

[3 3 1 2 3 0 1]
----------------------------
[3 2 0 4 1]
----------------------------
[2 3 3 2 2 2 3 3 2 3]


## 17. 정수형 데이터 카운팅 : unique(), bincount()

In [89]:
##### unique

arr = np.array(['a', 'b', 'b', 'c', 'a'])

print(len(arr))
print(np.unique(arr))   # unique() 는 중복된걸 빼고 보여줌
print(len(np.unique(arr)))  # 중복된 걸 뺀 자료의 수

print("----------------------------")

# return_counts 를 사용하게되면 몇번 중복됬는지를 알 수 있다.
# 아래에서 a는 2번중복, b는 2번중복, c는 1개만 있다는 것을 나타낸다.

idx, cnt = np.unique(arr, return_counts=True)
print(idx, cnt)

5
['a' 'b' 'c']
3
----------------------------
['a' 'b' 'c'] [2 2 1]


In [91]:
##### bincount : 발생하지 않은 사건에 대해서도 카운팅

arr = np.array([1, 1, 2, 2, 2, 3])

print(np.unique(arr, return_counts=True))
print(np.bincount(arr, minlength=6))   # [0 2 3 1 0 0] , 여기서 0은 0번, 1은 2번, 2는 3번, 3은 1번, 4는 0번, 5는 0번 나왔다는 의미

(array([1, 2, 3]), array([2, 3, 1], dtype=int64))
[0 2 3 1 0 0]


## 실습문제 : 영화 평점 데이터

+ https://grouplens.org

In [3]:
 #delimiter 는 구분문자,  파일안에 :: 를 기준으로 나누기 위함

data = np.loadtxt("data/ml-1m/ratings.dat", delimiter="::", dtype=np.int64)
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [4]:
print(data.shape)

(1000209, 4)


In [4]:
#첫행부터 20행까지 조회

print(data[0:20, :])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]]


In [24]:
#21행부터 30행까지 userid와 movieid만 조회

print(data[20:30, [0,1]])

[[   1 2321]
 [   1  720]
 [   1 1270]
 [   1  527]
 [   1 2340]
 [   1   48]
 [   1 1097]
 [   1 1721]
 [   1 1545]
 [   1  745]]


In [42]:
#전체 평점에 대한 평균이 얼마인가 조회

print(np.mean(data[ :, 2]))

3.581564453029317


In [28]:
#사용자별로 평점 평균(10명만 조회)

print("맨 처음 10명만 지정해서 평균 : ", np.mean(data[0:9, 2]))

userid = np.unique(data[:,0])
avg_score =[]

for id in userid:
    userid = data[data[:,0] == id,:]
    score = userid[:,2].mean()
    avg_score.append([id,score])
    
print(avg_score[:10])


맨 처음 10명만 지정해서 평균 4.111111111111111
[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606]]


In [33]:
# 전체 인원들 중 최고 평점 평균을 조회(userid와 함께 동시에 조회)

result = np.array(avg_score[:10])
idx_result = np.argmax(result[:, 1])
print(result[idx_result])

[7.         4.32258065]
